### ISSUE TITLE
Giving a title to a CKCircleMenuView button

### ISSUE THREAD

**Issue by SwiftRabbit** [JaNd3r/CKCircleMenuView#11]
Would be nice to be able to add a title to the buttons of the CKCircleMenuView.

Title could be underneath by default. 

![camera](https://user-images.githubusercontent.com/6453814/29038452-ba9c6dc0-7b75-11e7-9dee-c20d6713e739.png)

**Comment by JaNd3r** [comment]
Thank you for the suggestion. I experienced myself that it's sometimes hard to find intuitive and speaking icons, so an additional short text could be useful. I will have a look at it.

**Comment by JaNd3r** [comment]
I have added support for displaying a short title below each button. Title placement could use some tweaking though, especially for large and tiny font sizes (default is 11 pt).
