### ISSUE TITLE
Specifying a starting angle

### ISSUE THREAD

**Issue by SwiftRabbit** [JaNd3r/CKCircleMenuView#12]
Instead of having to specify a direction (CIRCLE_MENU_DIRECTION), it would be nice if we could specify a starting angle.

**Comment by JaNd3r** [comment]
The starting angle can be added to the parameter dictionary using the key CIRCLE_MENU_STARTING_ANGLE. It is optional. If the starting angle is set, the angle derived from CIRCLE_MENU_DIRECTION will be overridden.

**Comment by SwiftRabbit** [comment]
Thanks!

**Comment by JaNd3r** [comment]
You're welcome!

I have added this issue to the 0.4.0 milestone. I'm planning to release this by the end of this month. I will have a look at your other request (#11) and see, if I can get it into 0.4.0, too.
